### ISSUE TITLE
Missing Mutex unlock in OpcUa_ProxyStub_UpdateConfigString

### ISSUE THREAD

**Issue by cacamille3** [OPCFoundation/UA-AnsiC#57]
Missing 
```
#if OPCUA_USE_SYNCHRONISATION
    OPCUA_P_MUTEX_UNLOCK(OpcUa_ProxyStub_g_hGlobalsMutex);
#endif /* OPCUA_USE_SYNCHRONISATION */
```

in `OpcUa_ProxyStub_UpdateConfigString` after `OpcUa_BeginErrorHandling`;

**Comment by bernd-edlinger** [comment]
I noticed that error handling here is problematic because C99 snprintf
returns the number of chars that "would have been written", so a positive
number, so `iPos += iRes` may overflow.
```
    iRes = OpcUa_SnPrintfA(&OpcUa_ProxyStub_g_pConfigString[iPos], OPCUA_CONFIG_STRING_SIZE - iPos, "%s:%i\\", "iTcpTransport_MaxChunkCount", OpcUa_ProxyStub_g_Configuration.iTcpTransport_MaxChunkCount);
    if(iRes > 0){iPos += iRes;}else{OpcUa_GotoErrorWithStatus(OpcUa_BadOutOfMemory);}
```

While MSDN says Windows _snprint_s does return -1 in that case, it may be a problem in linux.
I tend to fixing that in the platform layer.
