### ISSUE TITLE
Potential memory leak in OpcUa_P_OpenSSL_X509_SelfSigned_Custom_Create

### ISSUE THREAD

**Issue by MarkusErlmann** [OPCFoundation/UA-AnsiC#66]
When `OPENSSL_realloc` returns a null pointer, the original memory of `pSerialNumber->Data` is lost.

A fix is available in #65.

**Comment by bernd-edlinger** [comment]
Thanks, but this is a way too complicated fix, because `pSerialNumber->Data` is always `NULL`.
Maybe just using `OPENSSL_malloc` would be more appropriate.

However I see a different issue here:

That is IF the GUID starts with 0x00, 0x00..0x7F the generated certificate uses an invalid ASN1
encoded serialNumber. One out of 512 created certificates have this anomaly.

I tried to create certificates that use such a serialNumber, but they seem to work with OpenSSL,
but it is possible that there are IOP issues with other libraries.

**Comment by MarkusErlmann** [comment]
@bernd-edlinger yes, if `pSerialNumber->Data` is always `NULL` here, I do also think that `OPENSSL_malloc` would be the better choice here.

Regarding the GUID issue: what would be the solution here?

**Comment by bernd-edlinger** [comment]
Are you affected by this issue?
I think it would be sufficient to look at the first byte and change it to 1 when it is 0.
I will put that on my TODO list.

**Comment by MarkusErlmann** [comment]
@bernd-edlinger No, I'm currently not affected. Fix sounds reasonable.

**Comment by bernd-edlinger** [comment]
fixed on trunk.
